
package gimnasio.Vistas;

import gimnasio.AccesoADatos.SocioData;
import gimnasio.Entidades.Socio;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.event.KeyEvent;
import javax.swing.ImageIcon;
import javax.swing.JTextField;
/**
 *
 * @author Javier
 */
public class FormSocio extends javax.swing.JInternalFrame {

    /**
     * Creates new form FormSocio
     */
    public FormSocio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImageIcon icon = new ImageIcon(getClass().getResource("/gimnasio/Imagenes/socio33.jpg"));
        Image image = icon.getImage();
        socio = new javax.swing.JDesktopPane(){     public void paintComponent(Graphics g){         g.drawImage(image,0,0,getWidth(),getHeight(),this);     } };
        jtCartelNombre = new javax.swing.JTextField();
        jtCartelApellido = new javax.swing.JTextField();
        jtCartelDni = new javax.swing.JTextField();
        jtCartelEdad = new javax.swing.JTextField();
        jtCartelCorreo = new javax.swing.JTextField();
        jtArea = new javax.swing.JTextField();
        jtApellidoSocio = new javax.swing.JTextField();
        jtNombreSocio = new javax.swing.JTextField();
        jtDniSocio = new javax.swing.JTextField();
        jtEdadSocio = new javax.swing.JTextField();
        jtCartelTelefono = new javax.swing.JTextField();
        jbLimpiar = new javax.swing.JButton();
        jbGuardar = new javax.swing.JButton();
        jbSalir = new javax.swing.JButton();
        jtCorreoSocio = new javax.swing.JTextField();
        jtFormularioInscripcion = new javax.swing.JTextField();
        jlError = new javax.swing.JLabel();
        jtNumero = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setTitle("Formulario de Gestíon de Socio");

        socio.setPreferredSize(new java.awt.Dimension(930, 520));

        jtCartelNombre.setBackground(new java.awt.Color(0, 0, 0));
        jtCartelNombre.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jtCartelNombre.setForeground(new java.awt.Color(255, 255, 255));
        jtCartelNombre.setText("Nombre");
        jtCartelNombre.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 51, 51), new java.awt.Color(0, 0, 0), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        jtCartelNombre.setCaretColor(new java.awt.Color(255, 51, 255));
        jtCartelNombre.setFocusable(false);

        jtCartelApellido.setBackground(new java.awt.Color(0, 0, 0));
        jtCartelApellido.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jtCartelApellido.setForeground(new java.awt.Color(255, 255, 255));
        jtCartelApellido.setText("Apellido");
        jtCartelApellido.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 51, 51), new java.awt.Color(0, 0, 0), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        jtCartelApellido.setCaretColor(new java.awt.Color(255, 51, 255));
        jtCartelApellido.setFocusable(false);

        jtCartelDni.setEditable(false);
        jtCartelDni.setBackground(new java.awt.Color(0, 0, 0));
        jtCartelDni.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jtCartelDni.setForeground(new java.awt.Color(255, 255, 255));
        jtCartelDni.setText("DNI");
        jtCartelDni.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 51, 51), new java.awt.Color(0, 0, 0), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        jtCartelDni.setFocusable(false);

        jtCartelEdad.setBackground(new java.awt.Color(0, 0, 0));
        jtCartelEdad.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jtCartelEdad.setForeground(new java.awt.Color(255, 255, 255));
        jtCartelEdad.setText("Edad");
        jtCartelEdad.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 51, 51), new java.awt.Color(0, 0, 0), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        jtCartelEdad.setFocusable(false);

        jtCartelCorreo.setBackground(new java.awt.Color(0, 0, 0));
        jtCartelCorreo.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jtCartelCorreo.setForeground(new java.awt.Color(255, 255, 255));
        jtCartelCorreo.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jtCartelCorreo.setText("Correo");
        jtCartelCorreo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 51, 51), new java.awt.Color(0, 0, 0), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        jtCartelCorreo.setFocusable(false);

        jtArea.setToolTipText("Ingrese el Código de Area sin el 0");
        jtArea.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtAreaFocusGained(evt);
            }
        });
        jtArea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtAreaKeyTyped(evt);
            }
        });

        jtApellidoSocio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtApellidoSocioFocusGained(evt);
            }
        });
        jtApellidoSocio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtApellidoSocioKeyTyped(evt);
            }
        });

        jtNombreSocio.setToolTipText("");
        jtNombreSocio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtNombreSocioFocusGained(evt);
            }
        });
        jtNombreSocio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtNombreSocioKeyTyped(evt);
            }
        });

        jtDniSocio.setToolTipText("Ingrese solo digitos del 0 al 9 sin puntos");
        jtDniSocio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtDniSocioFocusGained(evt);
            }
        });
        jtDniSocio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtDniSocioKeyTyped(evt);
            }
        });

        jtEdadSocio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtEdadSocioFocusGained(evt);
            }
        });
        jtEdadSocio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtEdadSocioKeyTyped(evt);
            }
        });

        jtCartelTelefono.setBackground(new java.awt.Color(0, 0, 0));
        jtCartelTelefono.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jtCartelTelefono.setForeground(new java.awt.Color(255, 255, 255));
        jtCartelTelefono.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jtCartelTelefono.setText("Teléfono");
        jtCartelTelefono.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 51, 51), new java.awt.Color(0, 0, 0), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        jtCartelTelefono.setFocusable(false);

        jbLimpiar.setBackground(new java.awt.Color(153, 153, 153));
        jbLimpiar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jbLimpiar.setForeground(new java.awt.Color(0, 0, 0));
        jbLimpiar.setText("Limpiar");
        jbLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimpiarActionPerformed(evt);
            }
        });

        jbGuardar.setBackground(new java.awt.Color(153, 153, 153));
        jbGuardar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jbGuardar.setForeground(new java.awt.Color(0, 0, 0));
        jbGuardar.setText("Guardar");
        jbGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGuardarActionPerformed(evt);
            }
        });

        jbSalir.setBackground(new java.awt.Color(153, 153, 153));
        jbSalir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jbSalir.setForeground(new java.awt.Color(0, 0, 0));
        jbSalir.setText("Salir");
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });

        jtCorreoSocio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtCorreoSocioFocusGained(evt);
            }
        });
        jtCorreoSocio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtCorreoSocioKeyTyped(evt);
            }
        });

        jtFormularioInscripcion.setBackground(new java.awt.Color(0, 0, 0));
        jtFormularioInscripcion.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jtFormularioInscripcion.setForeground(new java.awt.Color(255, 255, 255));
        jtFormularioInscripcion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtFormularioInscripcion.setText("FORMULARIO DE INSCRIPCIÓN DE SOCIO");
        jtFormularioInscripcion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 51, 51), new java.awt.Color(0, 0, 0), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        jtFormularioInscripcion.setCaretColor(new java.awt.Color(255, 51, 255));
        jtFormularioInscripcion.setFocusable(false);

        jlError.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jlError.setForeground(new java.awt.Color(255, 0, 51));
        jlError.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        jtNumero.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtNumeroFocusGained(evt);
            }
        });
        jtNumero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtNumeroKeyTyped(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Còd. Area");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Número");

        socio.setLayer(jtCartelNombre, javax.swing.JLayeredPane.DEFAULT_LAYER);
        socio.setLayer(jtCartelApellido, javax.swing.JLayeredPane.DEFAULT_LAYER);
        socio.setLayer(jtCartelDni, javax.swing.JLayeredPane.DEFAULT_LAYER);
        socio.setLayer(jtCartelEdad, javax.swing.JLayeredPane.DEFAULT_LAYER);
        socio.setLayer(jtCartelCorreo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        socio.setLayer(jtArea, javax.swing.JLayeredPane.DEFAULT_LAYER);
        socio.setLayer(jtApellidoSocio, javax.swing.JLayeredPane.DEFAULT_LAYER);
        socio.setLayer(jtNombreSocio, javax.swing.JLayeredPane.DEFAULT_LAYER);
        socio.setLayer(jtDniSocio, javax.swing.JLayeredPane.DEFAULT_LAYER);
        socio.setLayer(jtEdadSocio, javax.swing.JLayeredPane.DEFAULT_LAYER);
        socio.setLayer(jtCartelTelefono, javax.swing.JLayeredPane.DEFAULT_LAYER);
        socio.setLayer(jbLimpiar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        socio.setLayer(jbGuardar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        socio.setLayer(jbSalir, javax.swing.JLayeredPane.DEFAULT_LAYER);
        socio.setLayer(jtCorreoSocio, javax.swing.JLayeredPane.DEFAULT_LAYER);
        socio.setLayer(jtFormularioInscripcion, javax.swing.JLayeredPane.DEFAULT_LAYER);
        socio.setLayer(jlError, javax.swing.JLayeredPane.DEFAULT_LAYER);
        socio.setLayer(jtNumero, javax.swing.JLayeredPane.DEFAULT_LAYER);
        socio.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        socio.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout socioLayout = new javax.swing.GroupLayout(socio);
        socio.setLayout(socioLayout);
        socioLayout.setHorizontalGroup(
            socioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(socioLayout.createSequentialGroup()
                .addGroup(socioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(socioLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(socioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(socioLayout.createSequentialGroup()
                                .addGroup(socioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtCartelCorreo)
                                    .addComponent(jtCartelApellido)
                                    .addComponent(jtCartelEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(socioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(socioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jtNombreSocio, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                                        .addComponent(jtApellidoSocio))
                                    .addComponent(jtEdadSocio, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtCorreoSocio, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(socioLayout.createSequentialGroup()
                                .addGroup(socioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(socioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jtCartelNombre, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jtCartelDni, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jtCartelTelefono, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(socioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtDniSocio, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(socioLayout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtArea, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(socioLayout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jbGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jbLimpiar)
                                .addGap(18, 18, 18)
                                .addComponent(jbSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(socioLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jtFormularioInscripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(socioLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jlError, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        socioLayout.setVerticalGroup(
            socioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(socioLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jtFormularioInscripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(socioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtCartelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtNombreSocio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(socioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtCartelApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtApellidoSocio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(socioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtCartelDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtDniSocio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(socioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtCartelEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtEdadSocio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(socioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtCartelCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtCorreoSocio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(socioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtCartelTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlError, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 167, Short.MAX_VALUE)
                .addGroup(socioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbLimpiar)
                    .addComponent(jbGuardar)
                    .addComponent(jbSalir))
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(socio, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(socio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jbSalirActionPerformed

    private void jbGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGuardarActionPerformed
        // TODO add your handling code here:
        cargar();  
    }//GEN-LAST:event_jbGuardarActionPerformed

    private void jbLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimpiarActionPerformed
        // TODO add your handling code here:
        limpiar();
    }//GEN-LAST:event_jbLimpiarActionPerformed

    private void jtDniSocioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtDniSocioKeyTyped
        // TODO add your handling code here:
        if(!(Character.isDigit(evt.getKeyChar()))){
            jlError.setText("* Error en campo 'DNI': Debe ingresar solo números");
            evt.consume();
        }else{
            jlError.setText("");
        }
       if(jtDniSocio.getText().length() == 8){
           jlError.setText("* Error en campo 'DNI': Límite max: 8 dígitos");
            evt.consume();
       }
    }//GEN-LAST:event_jtDniSocioKeyTyped

    private void jtNombreSocioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtNombreSocioKeyTyped
        // TODO add your handling code here:
        final char keyChar = evt.getKeyChar();
        if (!(Character.isAlphabetic(keyChar) || (Character.isWhitespace(keyChar)) || keyChar == KeyEvent.VK_DELETE)) {
            jlError.setText("* Error en campo 'NOMBRE': Debe ingresar solo letras");
            evt.consume();
        }else{
            jlError.setText("");
        }
        if(jtNombreSocio.getText().length() >= 30){
            jlError.setText("* Error en campo 'NOMBRE': Límite max: 30 caracteres");
            evt.consume();
       }
        
    }//GEN-LAST:event_jtNombreSocioKeyTyped

    private void jtApellidoSocioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtApellidoSocioKeyTyped
        // TODO add your handling code here:
        final char keyChar = evt.getKeyChar();
        if (!(Character.isAlphabetic(keyChar) || (Character.isWhitespace(keyChar)) || keyChar == KeyEvent.VK_DELETE)) {
            jlError.setText("* Error en campo 'APELLIDO': Debe ingresar solo letras");
            evt.consume();
        }else{
            jlError.setText("");
        }
        if(jtApellidoSocio.getText().length() >= 30){
            jlError.setText("* Error en campo 'APELLIDO': Límite max: 30 caracteres");
            evt.consume();
       }
    }//GEN-LAST:event_jtApellidoSocioKeyTyped

    private void jtCorreoSocioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtCorreoSocioKeyTyped
        // TODO add your handling code here:
        final char keyChar = evt.getKeyChar();
        if (Character.isWhitespace(keyChar) || keyChar == KeyEvent.VK_DELETE) {
               evt.consume();
        }else{
            jlError.setText("");
        }
        if(jtCorreoSocio.getText().length() >= 50){
            jlError.setText("* Error en campo 'CORREO': Límite max: 50 caracteres");
            evt.consume();
       }
    }//GEN-LAST:event_jtCorreoSocioKeyTyped

    private void jtEdadSocioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtEdadSocioKeyTyped
        // TODO add your handling code here:
        final int keyChar = evt.getKeyChar();
        if(!(Character.isDigit(keyChar))){
            jlError.setText("* Error en campo 'EDAD': Debe ingresar solo números");
            evt.consume();
        }else{
            jlError.setText("");
        }
       if(jtEdadSocio.getText().length() == 2){
           jlError.setText("* Error en campo 'EDAD': Límite max: 99 años");
            evt.consume();
       }
    }//GEN-LAST:event_jtEdadSocioKeyTyped

    private void jtAreaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtAreaKeyTyped
        // TODO add your handling code here:
        final int keyChar = evt.getKeyChar();
        if(!(Character.isDigit(keyChar))){
            jlError.setText("* Error en campo 'AREA': Debe ingresar solo números");
            evt.consume();
        }else{
            jlError.setText("");
        }
       if(jtArea.getText().length() == 6){
           jlError.setText("* Error en campo 'AREA': Límite max: 6 dígitos");
            evt.consume();
       }
    }//GEN-LAST:event_jtAreaKeyTyped

    private void jtNombreSocioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtNombreSocioFocusGained
        // TODO add your handling code here:
        jtNombreSocio.setText(null); 
        jtNombreSocio.setForeground(Color.BLACK);
    }//GEN-LAST:event_jtNombreSocioFocusGained

    private void jtApellidoSocioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtApellidoSocioFocusGained
        // TODO add your handling code here:
        jtApellidoSocio.setText(null); 
        jtApellidoSocio.setForeground(Color.BLACK);
    }//GEN-LAST:event_jtApellidoSocioFocusGained

    private void jtDniSocioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtDniSocioFocusGained
        // TODO add your handling code here:
        jtDniSocio.setText(null); 
        jtDniSocio.setForeground(Color.BLACK);
    }//GEN-LAST:event_jtDniSocioFocusGained

    private void jtEdadSocioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtEdadSocioFocusGained
        // TODO add your handling code here:
        jtEdadSocio.setText(null); 
        jtEdadSocio.setForeground(Color.BLACK);
    }//GEN-LAST:event_jtEdadSocioFocusGained

    private void jtCorreoSocioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtCorreoSocioFocusGained
        // TODO add your handling code here:
        jtCorreoSocio.setText(null); 
        jtCorreoSocio.setForeground(Color.BLACK);
    }//GEN-LAST:event_jtCorreoSocioFocusGained

    private void jtAreaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtAreaFocusGained
        // TODO add your handling code here:
        jtArea.setText(null); 
        jtArea.setForeground(Color.BLACK);
    }//GEN-LAST:event_jtAreaFocusGained

    private void jtNumeroFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtNumeroFocusGained
        // TODO add your handling code here:
        jtNumero.setText(null); 
        jtNumero.setForeground(Color.BLACK);
    }//GEN-LAST:event_jtNumeroFocusGained

    private void jtNumeroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtNumeroKeyTyped
        // TODO add your handling code here:
          final int keyChar = evt.getKeyChar();
        if(!(Character.isDigit(keyChar))){
            jlError.setText("* Error en 'NUMERO': Debe ingresar solo números");
            evt.consume();
        }else{
            jlError.setText("");
        }
       if(jtNumero.getText().length() == 14){
           jlError.setText("* Error en 'NUMERO': Límite max: 14 dígitos");
            evt.consume();
       }
            
    }//GEN-LAST:event_jtNumeroKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton jbGuardar;
    private javax.swing.JButton jbLimpiar;
    private javax.swing.JButton jbSalir;
    private javax.swing.JLabel jlError;
    private javax.swing.JTextField jtApellidoSocio;
    private javax.swing.JTextField jtArea;
    private javax.swing.JTextField jtCartelApellido;
    private javax.swing.JTextField jtCartelCorreo;
    private javax.swing.JTextField jtCartelDni;
    private javax.swing.JTextField jtCartelEdad;
    private javax.swing.JTextField jtCartelNombre;
    private javax.swing.JTextField jtCartelTelefono;
    private javax.swing.JTextField jtCorreoSocio;
    private javax.swing.JTextField jtDniSocio;
    private javax.swing.JTextField jtEdadSocio;
    private javax.swing.JTextField jtFormularioInscripcion;
    private javax.swing.JTextField jtNombreSocio;
    private javax.swing.JTextField jtNumero;
    private javax.swing.JDesktopPane socio;
    // End of variables declaration//GEN-END:variables

    public void cargar(){
           try{
                Socio socio = new Socio();
                socio.setNombre(jtNombreSocio.getText());
                socio.setApellido(jtApellidoSocio.getText());
                socio.setDni(jtDniSocio.getText());
                socio.setCorreo(jtCorreoSocio.getText());
                socio.setContador_asistencia(12);
                socio.setEstado(true);
                socio.setTelefono(jtArea.getText());
                socio.setEdad(Integer.parseInt(jtEdadSocio.getText()));    
                if(camposVacios()) throw new NumberFormatException();
                SocioData socioData = new SocioData();
                socioData.guardarSocio(socio);
            }catch(NumberFormatException ex){
              campoObligatorio();
            } 
        
    }
    
    public void limpiar(){
        jtNombreSocio.setText(null);
        jtApellidoSocio.setText(null);
        jtCorreoSocio.setText(null);
        jtDniSocio.setText(null);
        jtEdadSocio.setText(null);
        jtArea.setText(null);
        jtNumero.setText(null);
        jlError.setText(null);
    }
    
    public void campoObligatorio(){
        setCamposVacios(jtNombreSocio);
        setCamposVacios(jtApellidoSocio);
        setCamposVacios(jtCorreoSocio);
        setCamposVacios(jtDniSocio);
        setCamposVacios(jtEdadSocio);
        setCamposVacios(jtArea);
        setCamposVacios(jtNumero);
        jlError.setText("* Debe completar todos los campos");
    }
    
    public void setCamposVacios(JTextField jtSocio){
         if(jtSocio.getText().equals("")){
            jtSocio.setForeground(Color.red);
            jtSocio.setText("                * Campo Obligatorio");
        }
    }
    
    public boolean camposVacios() {
    JTextField[] campos = {jtNombreSocio, jtApellidoSocio, jtDniSocio, jtCorreoSocio, jtArea, jtNumero};

    for (JTextField campo : campos) {
        if (campo.getText().isEmpty() || campo.getText().contains("*")) {
            return true;
        }
    }
    return false;
    }
}
