
package gimnasio.Vistas;

import gimnasio.AccesoADatos.SocioData;
import gimnasio.Entidades.Socio;
import gimnasio.Entidades.Membresia;
import gimnasio.AccesoADatos.MembresiaData;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.event.KeyEvent;
import javax.swing.ImageIcon;
import javax.swing.JTextField;
/**
 *
 * @author Javier
 */
public class FormSocio extends javax.swing.JInternalFrame {

    /**
     * Creates new form FormSocio
     */
    public FormSocio() {
        initComponents();
        jtIdSocio.setText(String.valueOf(ultimoIdSocio()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImageIcon icon = new ImageIcon(getClass().getResource("/gimnasio/Imagenes/socio33.jpg"));
        Image image = icon.getImage();
        DesktopPane = new javax.swing.JDesktopPane(){     public void paintComponent(Graphics g){         g.drawImage(image,0,0,getWidth(),getHeight(),this);     } };
        jtCartelNombre = new javax.swing.JTextField();
        jtCartelApellido = new javax.swing.JTextField();
        jtCartelDni = new javax.swing.JTextField();
        jtCartelEdad = new javax.swing.JTextField();
        jtCartelCorreo = new javax.swing.JTextField();
        jtArea = new javax.swing.JTextField();
        jtApellidoSocio = new javax.swing.JTextField();
        jtNombreSocio = new javax.swing.JTextField();
        jtDniSocio = new javax.swing.JTextField();
        jtEdadSocio = new javax.swing.JTextField();
        jtCartelTelefono = new javax.swing.JTextField();
        jtAMembresia = new javax.swing.JButton();
        jbGuardar = new javax.swing.JButton();
        jbLimpiar = new javax.swing.JButton();
        jtCorreoSocio = new javax.swing.JTextField();
        jtFormularioInscripcion = new javax.swing.JTextField();
        jlError = new javax.swing.JLabel();
        jtNumero = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtCartelIdSocio = new javax.swing.JTextField();
        jtIdSocio = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("Formulario de Gestíon de Socio");

        DesktopPane.setPreferredSize(new java.awt.Dimension(940, 540));
        DesktopPane.setName("DesktopPane"); // NOI18N

        jtCartelNombre.setBackground(new java.awt.Color(0, 0, 0));
        jtCartelNombre.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jtCartelNombre.setForeground(new java.awt.Color(255, 255, 255));
        jtCartelNombre.setText("Nombre");
        jtCartelNombre.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 51, 51), new java.awt.Color(0, 0, 0), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        jtCartelNombre.setCaretColor(new java.awt.Color(255, 51, 255));
        jtCartelNombre.setFocusable(false);

        jtCartelApellido.setBackground(new java.awt.Color(0, 0, 0));
        jtCartelApellido.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jtCartelApellido.setForeground(new java.awt.Color(255, 255, 255));
        jtCartelApellido.setText("Apellido");
        jtCartelApellido.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 51, 51), new java.awt.Color(0, 0, 0), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        jtCartelApellido.setCaretColor(new java.awt.Color(255, 51, 255));
        jtCartelApellido.setFocusable(false);

        jtCartelDni.setEditable(false);
        jtCartelDni.setBackground(new java.awt.Color(0, 0, 0));
        jtCartelDni.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jtCartelDni.setForeground(new java.awt.Color(255, 255, 255));
        jtCartelDni.setText("DNI");
        jtCartelDni.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 51, 51), new java.awt.Color(0, 0, 0), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        jtCartelDni.setFocusable(false);

        jtCartelEdad.setBackground(new java.awt.Color(0, 0, 0));
        jtCartelEdad.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jtCartelEdad.setForeground(new java.awt.Color(255, 255, 255));
        jtCartelEdad.setText("Edad");
        jtCartelEdad.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 51, 51), new java.awt.Color(0, 0, 0), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        jtCartelEdad.setFocusable(false);

        jtCartelCorreo.setBackground(new java.awt.Color(0, 0, 0));
        jtCartelCorreo.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jtCartelCorreo.setForeground(new java.awt.Color(255, 255, 255));
        jtCartelCorreo.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jtCartelCorreo.setText("Correo");
        jtCartelCorreo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 51, 51), new java.awt.Color(0, 0, 0), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        jtCartelCorreo.setFocusable(false);

        jtArea.setToolTipText("Ingrese el Código de Area sin el 0");
        jtArea.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtAreaFocusGained(evt);
            }
        });
        jtArea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtAreaKeyTyped(evt);
            }
        });

        jtApellidoSocio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtApellidoSocioFocusGained(evt);
            }
        });
        jtApellidoSocio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtApellidoSocioKeyTyped(evt);
            }
        });

        jtNombreSocio.setToolTipText("");
        jtNombreSocio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtNombreSocioFocusGained(evt);
            }
        });
        jtNombreSocio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtNombreSocioKeyTyped(evt);
            }
        });

        jtDniSocio.setToolTipText("");
        jtDniSocio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtDniSocioFocusGained(evt);
            }
        });
        jtDniSocio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtDniSocioKeyTyped(evt);
            }
        });

        jtEdadSocio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtEdadSocioFocusGained(evt);
            }
        });
        jtEdadSocio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtEdadSocioKeyTyped(evt);
            }
        });

        jtCartelTelefono.setBackground(new java.awt.Color(0, 0, 0));
        jtCartelTelefono.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jtCartelTelefono.setForeground(new java.awt.Color(255, 255, 255));
        jtCartelTelefono.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jtCartelTelefono.setText("Teléfono");
        jtCartelTelefono.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 51, 51), new java.awt.Color(0, 0, 0), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        jtCartelTelefono.setFocusable(false);

        jtAMembresia.setBackground(new java.awt.Color(153, 153, 153));
        jtAMembresia.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jtAMembresia.setForeground(new java.awt.Color(0, 0, 0));
        jtAMembresia.setText("Membresia");
        jtAMembresia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtAMembresiaActionPerformed(evt);
            }
        });

        jbGuardar.setBackground(new java.awt.Color(153, 153, 153));
        jbGuardar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jbGuardar.setForeground(new java.awt.Color(0, 0, 0));
        jbGuardar.setText("Guardar");
        jbGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGuardarActionPerformed(evt);
            }
        });

        jbLimpiar.setBackground(new java.awt.Color(153, 153, 153));
        jbLimpiar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jbLimpiar.setForeground(new java.awt.Color(0, 0, 0));
        jbLimpiar.setText("Limpiar");
        jbLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimpiarActionPerformed(evt);
            }
        });

        jtCorreoSocio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtCorreoSocioFocusGained(evt);
            }
        });
        jtCorreoSocio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtCorreoSocioKeyTyped(evt);
            }
        });

        jtFormularioInscripcion.setBackground(new java.awt.Color(0, 0, 0));
        jtFormularioInscripcion.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jtFormularioInscripcion.setForeground(new java.awt.Color(255, 255, 255));
        jtFormularioInscripcion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtFormularioInscripcion.setText("FORMULARIO DE INSCRIPCIÓN DE SOCIO");
        jtFormularioInscripcion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 51, 51), new java.awt.Color(0, 0, 0), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        jtFormularioInscripcion.setCaretColor(new java.awt.Color(255, 51, 255));
        jtFormularioInscripcion.setFocusable(false);

        jlError.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jlError.setForeground(new java.awt.Color(255, 0, 51));
        jlError.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        jtNumero.setToolTipText("Celulares: Ingrese el número sin el 15");
        jtNumero.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtNumeroFocusGained(evt);
            }
        });
        jtNumero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtNumeroKeyTyped(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Còd. Area");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Número");

        jtCartelIdSocio.setBackground(new java.awt.Color(0, 0, 0));
        jtCartelIdSocio.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jtCartelIdSocio.setForeground(new java.awt.Color(255, 255, 255));
        jtCartelIdSocio.setText("ID Socio");
        jtCartelIdSocio.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 51, 51), new java.awt.Color(0, 0, 0), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        jtCartelIdSocio.setCaretColor(new java.awt.Color(255, 51, 255));
        jtCartelIdSocio.setFocusable(false);

        jtIdSocio.setToolTipText("");
        jtIdSocio.setFocusable(false);
        jtIdSocio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtIdSocioFocusGained(evt);
            }
        });
        jtIdSocio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtIdSocioKeyTyped(evt);
            }
        });

        DesktopPane.setLayer(jtCartelNombre, javax.swing.JLayeredPane.DEFAULT_LAYER);
        DesktopPane.setLayer(jtCartelApellido, javax.swing.JLayeredPane.DEFAULT_LAYER);
        DesktopPane.setLayer(jtCartelDni, javax.swing.JLayeredPane.DEFAULT_LAYER);
        DesktopPane.setLayer(jtCartelEdad, javax.swing.JLayeredPane.DEFAULT_LAYER);
        DesktopPane.setLayer(jtCartelCorreo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        DesktopPane.setLayer(jtArea, javax.swing.JLayeredPane.DEFAULT_LAYER);
        DesktopPane.setLayer(jtApellidoSocio, javax.swing.JLayeredPane.DEFAULT_LAYER);
        DesktopPane.setLayer(jtNombreSocio, javax.swing.JLayeredPane.DEFAULT_LAYER);
        DesktopPane.setLayer(jtDniSocio, javax.swing.JLayeredPane.DEFAULT_LAYER);
        DesktopPane.setLayer(jtEdadSocio, javax.swing.JLayeredPane.DEFAULT_LAYER);
        DesktopPane.setLayer(jtCartelTelefono, javax.swing.JLayeredPane.DEFAULT_LAYER);
        DesktopPane.setLayer(jtAMembresia, javax.swing.JLayeredPane.DEFAULT_LAYER);
        DesktopPane.setLayer(jbGuardar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        DesktopPane.setLayer(jbLimpiar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        DesktopPane.setLayer(jtCorreoSocio, javax.swing.JLayeredPane.DEFAULT_LAYER);
        DesktopPane.setLayer(jtFormularioInscripcion, javax.swing.JLayeredPane.DEFAULT_LAYER);
        DesktopPane.setLayer(jlError, javax.swing.JLayeredPane.DEFAULT_LAYER);
        DesktopPane.setLayer(jtNumero, javax.swing.JLayeredPane.DEFAULT_LAYER);
        DesktopPane.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        DesktopPane.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        DesktopPane.setLayer(jtCartelIdSocio, javax.swing.JLayeredPane.DEFAULT_LAYER);
        DesktopPane.setLayer(jtIdSocio, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout DesktopPaneLayout = new javax.swing.GroupLayout(DesktopPane);
        DesktopPane.setLayout(DesktopPaneLayout);
        DesktopPaneLayout.setHorizontalGroup(
            DesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DesktopPaneLayout.createSequentialGroup()
                .addGroup(DesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DesktopPaneLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(DesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(DesktopPaneLayout.createSequentialGroup()
                                .addGroup(DesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtCartelCorreo)
                                    .addComponent(jtCartelApellido)
                                    .addComponent(jtCartelEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(DesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(DesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jtNombreSocio, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                                        .addComponent(jtApellidoSocio))
                                    .addComponent(jtEdadSocio, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtCorreoSocio, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(DesktopPaneLayout.createSequentialGroup()
                                .addGroup(DesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(DesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jtCartelNombre, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jtCartelDni, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jtCartelTelefono, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(DesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtDniSocio, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(DesktopPaneLayout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtArea, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(DesktopPaneLayout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jbGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jtAMembresia)
                                .addGap(18, 18, 18)
                                .addComponent(jbLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(DesktopPaneLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jtFormularioInscripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(DesktopPaneLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jlError, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(DesktopPaneLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jtCartelIdSocio, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtIdSocio, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        DesktopPaneLayout.setVerticalGroup(
            DesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DesktopPaneLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jtFormularioInscripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(DesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtCartelIdSocio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtIdSocio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(DesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtCartelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtNombreSocio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtCartelApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtApellidoSocio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtCartelDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtDniSocio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtCartelEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtEdadSocio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtCartelCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtCorreoSocio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtCartelTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlError, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 140, Short.MAX_VALUE)
                .addGroup(DesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtAMembresia)
                    .addComponent(jbGuardar)
                    .addComponent(jbLimpiar))
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DesktopPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DesktopPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimpiarActionPerformed
        // TODO add your handling code here:
      limpiarTodo();
       
    }//GEN-LAST:event_jbLimpiarActionPerformed

    private void jbGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGuardarActionPerformed
        // TODO add your handling code here:
        cargar();  
    }//GEN-LAST:event_jbGuardarActionPerformed

    private void jtAMembresiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtAMembresiaActionPerformed
        FormMembresia membresiaFrame = new FormMembresia();
        DesktopPane.add(membresiaFrame);
        membresiaFrame.setVisible(true);
       
    }//GEN-LAST:event_jtAMembresiaActionPerformed

    private void jtDniSocioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtDniSocioKeyTyped
        String campo = "DNI";
        int limite = 8;
        controlSoloNumeros(evt, campo, limite, jtDniSocio);
    }//GEN-LAST:event_jtDniSocioKeyTyped

    private void jtNombreSocioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtNombreSocioKeyTyped
        String campo = "NOMBRE";
        controlSoloLetras(evt, campo, jtNombreSocio);  
    }//GEN-LAST:event_jtNombreSocioKeyTyped

    private void jtApellidoSocioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtApellidoSocioKeyTyped
        String campo = "APELLIDO";
        controlSoloLetras(evt, campo, jtApellidoSocio);
    }//GEN-LAST:event_jtApellidoSocioKeyTyped

    private void jtCorreoSocioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtCorreoSocioKeyTyped
        // TODO add your handling code here:
        final char keyChar = evt.getKeyChar();
        if (Character.isWhitespace(keyChar) || keyChar == KeyEvent.VK_DELETE) {
               evt.consume();
        }else{
            jlError.setText("");
        }
        if(jtCorreoSocio.getText().length() >= 50){
            jlError.setText("* Error en campo 'CORREO': Límite max: 50 caracteres");
            evt.consume();
       }
    }//GEN-LAST:event_jtCorreoSocioKeyTyped

    private void jtEdadSocioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtEdadSocioKeyTyped
       String campo = "EDAD";
        int limite = 2;
        controlSoloNumeros(evt, campo, limite, jtEdadSocio);
    }//GEN-LAST:event_jtEdadSocioKeyTyped

    private void jtAreaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtAreaKeyTyped
        String campo = "AREA";
        int limite = 6;
        controlSoloNumeros(evt, campo, limite, jtArea);
    }//GEN-LAST:event_jtAreaKeyTyped

    private void jtNombreSocioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtNombreSocioFocusGained
        limpiarCampo(jtNombreSocio);
    }//GEN-LAST:event_jtNombreSocioFocusGained

    private void jtApellidoSocioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtApellidoSocioFocusGained
        limpiarCampo(jtApellidoSocio);
    }//GEN-LAST:event_jtApellidoSocioFocusGained

    private void jtDniSocioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtDniSocioFocusGained
        limpiarCampo(jtDniSocio);
    }//GEN-LAST:event_jtDniSocioFocusGained

    private void jtEdadSocioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtEdadSocioFocusGained
        limpiarCampo(jtEdadSocio);
    }//GEN-LAST:event_jtEdadSocioFocusGained

    private void jtCorreoSocioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtCorreoSocioFocusGained
        limpiarCampo(jtCorreoSocio);
    }//GEN-LAST:event_jtCorreoSocioFocusGained

    private void jtAreaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtAreaFocusGained
        limpiarCampo(jtArea);
    }//GEN-LAST:event_jtAreaFocusGained

    private void jtNumeroFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtNumeroFocusGained
        limpiarCampo(jtNumero);
    }//GEN-LAST:event_jtNumeroFocusGained

    private void jtNumeroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtNumeroKeyTyped
       String campo = "NUMERO";
       int limite = 14;
        controlSoloNumeros(evt, campo, limite, jtNumero);
            
    }//GEN-LAST:event_jtNumeroKeyTyped

    private void jtIdSocioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtIdSocioFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jtIdSocioFocusGained

    private void jtIdSocioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtIdSocioKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jtIdSocioKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane DesktopPane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton jbGuardar;
    private javax.swing.JButton jbLimpiar;
    private javax.swing.JLabel jlError;
    private javax.swing.JButton jtAMembresia;
    private javax.swing.JTextField jtApellidoSocio;
    private javax.swing.JTextField jtArea;
    private javax.swing.JTextField jtCartelApellido;
    private javax.swing.JTextField jtCartelCorreo;
    private javax.swing.JTextField jtCartelDni;
    private javax.swing.JTextField jtCartelEdad;
    private javax.swing.JTextField jtCartelIdSocio;
    private javax.swing.JTextField jtCartelNombre;
    private javax.swing.JTextField jtCartelTelefono;
    private javax.swing.JTextField jtCorreoSocio;
    private javax.swing.JTextField jtDniSocio;
    private javax.swing.JTextField jtEdadSocio;
    private javax.swing.JTextField jtFormularioInscripcion;
    private javax.swing.JTextField jtIdSocio;
    private javax.swing.JTextField jtNombreSocio;
    private javax.swing.JTextField jtNumero;
    // End of variables declaration//GEN-END:variables

    private void cargar(){
           try{
                Socio socio = new Socio();
                socio.setNombre(jtNombreSocio.getText());
                socio.setApellido(jtApellidoSocio.getText());
                socio.setDni(jtDniSocio.getText());
                socio.setCorreo(jtCorreoSocio.getText());
                socio.setContador_asistencia(12);
                socio.setEstado(true);
                socio.setTelefono(jtArea.getText()+jtNumero.getText());
                socio.setEdad(Integer.parseInt(jtEdadSocio.getText()));    
                if(camposVacios()) throw new NumberFormatException();
                validarLongitudMin();
                //validarRangoMin();
                SocioData socioData = new SocioData();
                if(socioData.guardarSocio(socio)){
                    ultimoIdSocio();
                    limpiarTodo();
                }
            }catch(NumberFormatException ex){
                campoObligatorio();
            }catch(Exception ec) {
            }
    }
    
    private void limpiarTodo(){
        JTextField[] campos = {jtNombreSocio, jtApellidoSocio, jtDniSocio, jtCorreoSocio, jtEdadSocio, jtArea, jtNumero};
        for (JTextField campo : campos) {
            campo.setText(null);
        }
        jlError.setText(null);
    }
    
    private void campoObligatorio(){
        JTextField[] campos = {jtNombreSocio, jtApellidoSocio, jtDniSocio, jtCorreoSocio, jtEdadSocio, jtArea, jtNumero};
        for (JTextField campo : campos) {
            setCampoObligatorio(campo);
        }
        jlError.setText("* Debe completar todos los campos");
    }
    
    private void setCampoObligatorio(JTextField jtSocio){
         if(jtSocio.getText().equals("")){
            jtSocio.setForeground(Color.red);
            jtSocio.setText("                * Campo Obligatorio");
        }
    }
    
    public boolean camposVacios() {
    JTextField[] campos = {jtNombreSocio, jtApellidoSocio, jtDniSocio, jtCorreoSocio, jtArea, jtNumero};
    for (JTextField campo : campos) {
        if (campo.getText().isEmpty() || campo.getText().contains("*")) {
            return true;
        }
    }
    return false;
    }
    
    public void limpiarCampo(JTextField socio){
        if(socio.getText().contains("*")) socio.setText(null);
         
        socio.setForeground(Color.BLACK);
    }
    
    private void controlSoloLetras(java.awt.event.KeyEvent evt, String campo, JTextField jtextfield){
        final char keyChar = evt.getKeyChar();
        if (!(Character.isAlphabetic(keyChar) || (Character.isWhitespace(keyChar)) || keyChar == KeyEvent.VK_DELETE)) {
            jlError.setText("* Error en campo '"+campo+"': Debe ingresar solo letras");
            evt.consume();
        }else{
            jlError.setText("");
        }
        if(jtextfield.getText().length() >= 30){
            jlError.setText("* Error en campo '"+campo+"' Longitud max: 30 caracteres");
            evt.consume();
        }
         
    }
    
    private void controlSoloNumeros(java.awt.event.KeyEvent evt, String campo, int limite, JTextField jtextfield){
        final int keyChar = evt.getKeyChar();
        if(!(Character.isDigit(keyChar))){
            jlError.setText("* Error en '"+campo+"': Debe ingresar solo números");
            evt.consume();
        }else{
            jlError.setText("");
        }
        if(jtextfield.getText().length() == limite){
           jlError.setText("* Error en '"+campo+"': Longitud max: "+limite+" dígitos");
            evt.consume();
        }
    }
       
    private void validarLongitudMin() throws Exception{
        validarLongitud(jtNombreSocio.getText(), "NOMBRE", 3);
        validarLongitud(jtApellidoSocio.getText(), "APELLIDO", 3);
        validarLongitud(jtDniSocio.getText(), "DNI", 7);
        validarRangoMin();
        validarLongitud(jtArea.getText(), "AREA", 2);
        validarLongitud(jtNumero.getText(), "NUMERO", 7);
    }

    private void validarLongitud(String campo, String nombreCampo, int longitudMinima) throws Exception{
        if(campo.length() < longitudMinima){
            jlError.setText("* Error en campo '"+nombreCampo+"' Longitud min: "+longitudMinima+" caracteres"); 
            throw new Exception();
        }
    }
    
    private void validarRangoMin() throws Exception{
        validarRango(Integer.parseInt(jtDniSocio.getText()), "DNI", 1000000);
        validarRango(Integer.parseInt(jtEdadSocio.getText()), "EDAD", 6);
    }
    
    private void validarRango(int campo, String nombreCampo, int rangoMinimo) throws Exception{
        if(campo < rangoMinimo){
            jlError.setText("* Error en campo '"+nombreCampo+"' Rango min: "+rangoMinimo); 
            throw new Exception();
        }
    }
    
    private int ultimoIdSocio(){
        SocioData sociodata = new SocioData();
        int id = sociodata.ultimoId();
       // System.out.println("el id es: "+id);
       return id+1;
    }
}
